### ISSUE TITLE
non-deterministic symbol lookup error in pr2_etherCAT on lucid  (ros ticket #4852)

### ISSUE THREAD

**Issue by ahendrix** [PR2/pr2_ethercat_drivers#44]
On prm1, frequently when starting the robot, we get an error message:

{{{
[ INFO] [1288139078.908006914]: Xml file not found, reading from parameter server
/opt/ros/cturtle/stacks/pr2_robot/pr2_etherCAT/pr2_etherCAT: symbol lookup error: /opt/ros/cturtle/stacks/pr2_controllers/ethercat_trigger_controllers/lib/libethercat_trigger_controllers.so: undefined symbol: _ZN5boost18co\
ndition_variable4waitERNS_11unique_lockINS_5mutexEEE
[INFO] 1288139079.470571: Loading controller configuration on parameter server...
Traceback (most recent call last):
  File "/opt/ros/cturtle/stacks/pr2_mechanism/pr2_controller_manager/scripts/spawner", line 159, in <module>
    if __name__ == '**main**': main()
  File "/opt/ros/cturtle/stacks/pr2_mechanism/pr2_controller_manager/scripts/spawner", line 137, in main
    resp = load_controller(name)
  File "/opt/ros/cturtle/ros/core/rospy/src/rospy/impl/tcpros_service.py", line 418, in **call**
    return self.call(_args, *_kwds)
  File "/opt/ros/cturtle/ros/core/rospy/src/rospy/impl/tcpros_service.py", line 487, in call
    raise ServiceException("unable to connect to service: %s"%e)
rospy.service.ServiceException: unable to connect to service: [Errno 104] Connection reset by peer
[ERROR] 1288139079.603237: AsynchronousUpdater failed with exception: unable to connect to service: [Errno 104] Connection reset by peer
[ERROR] 1288139079.603971: AsynchronousUpdater failed with exception: unable to connect to service: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/opt/ros/cturtle/stacks/pr2_mechanism/pr2_controller_manager/scripts/spawner", line 159, in <module>
    if **name** == '**main**': main()
  File "/opt/ros/cturtle/stacks/pr2_mechanism/pr2_controller_manager/scripts/spawner", line 137, in main
    resp = load_controller(name)
  File "/opt/ros/cturtle/ros/core/rospy/src/rospy/impl/tcpros_service.py", line 418, in **call**
    return self.call(_args, *_kwds)
  File "/opt/ros/cturtle/ros/core/rospy/src/rospy/impl/tcpros_service.py", line 507, in call
    raise ServiceException("transport error completing service call: %s"%(str(e)))
rospy.service.ServiceException: transport error completing service call: unable to receive data from sender, check sender's logs for details
[WARN] 1288139079.612872: Spawner couldn't reach pr2_controller_manager to take down controllers.
[WARN] 1288139079.613128: Spawner couldn't reach pr2_controller_manager to take down controllers.
[INFO] 1288139079.618595: Arm selection was set to "auto".  Chose to calibrate using "both"
[INFO] 1288139079.620719: Bringing down calibration node
Exception rospy.service.ServiceException: ServiceException('unable to connect to service: [Errno 111] Connection refused',) in <bound method CalibrateParallel.__del__ of <__main__.CalibrateParallel instance at 0x25fc908>> \
ignored
Traceback (most recent call last):
  File "/opt/ros/cturtle/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 418, in <module>
    if **name** == '**main**': main()
  File "/opt/ros/cturtle/stacks/pr2_robot/pr2_bringup/scripts/calibrate_pr2.py", line 397, in main
    del arm
UnboundLocalError: local variable 'arm' referenced before assignment
[realtime_loop-1] process has died [pid 7673, exit code 127].
log files: /u/hsiao/.ros/log/c37f3d80-e15f-11df-96dc-00238bdfdf6a/realtime_loop-1_.log
[l_forearm_cam_trigger_spawner-24] process has died [pid 7845, exit code 1].
log files: /u/hsiao/.ros/log/c37f3d80-e15f-11df-96dc-00238bdfdf6a/l_forearm_cam_trigger_spawner-24_.log
[spawner_camera_synchronizer-10] process has died [pid 7727, exit code 1].
log files: /u/hsiao/.ros/log/c37f3d80-e15f-11df-96dc-00238bdfdf6a/spawner_camera_synchronizer-10*.log
[calibrate_pr2-2] process has died [pid 7676, exit code 1].
}}}

However, it does not appear to happen deterministically.

trac data:
- Owner: **wheeler**
- Reporter: **leibs**
- Reported at: **Tue Oct 26 17:46:58 2010**
- URL: https://code.ros.org/trac/wg-ros-pkg/ticket/4852

**Comment by ahendrix** [comment]
[leibs] This actually seems to be a repeat of: #4682 again.
